name: prebuild

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: darwin
            os: macos-11
            node: x64
          - name: linux
            os: ubuntu-latest
          - name: win32
            os: windows-2019
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - name: Install dependencies (ubuntu-latest)
        # Use g++-9 only on versions after 'ubuntu-18.04'
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt -qq update
          sudo apt install -y g++-9
          export CC="g++-9"
      - run: npm install --ignore-scripts
      - run: npm run prebuild-${{ matrix.name }}
      - run: tar -zcvf ${{ matrix.name }}.tar.gz -C prebuilds .
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: prebuilds/
          if-no-files-found: error
      - if: failure()
        run: npx shx ls -lA
release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: prebuilds
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}